spring.application.name=portfolio

firebase.credentials.path=firebase-service-account.json
payment.url=https://pay.monime.io/099220233
app.seed-data=false

resend.api-key=${RESEND_API_KEY}
resend.from-email=onboarding@resend.dev
contact.receiver-email=abduldeenkamara06@gmail.com

admin.password=${ADMIN_PASSWORD}

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB